# Prometheus configuration for Cloud Infrastructure Platform monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Rule files to load
rule_files:
  - "alert-rules.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape the Cloud Platform application metrics
  - job_name: "cloud-platform"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["cloud-platform:5000"]
    basic_auth:
      username: "${PROMETHEUS_USERNAME}"
      password: "${PROMETHEUS_PASSWORD}"

  # Scrape Node Exporter metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Scrape PostgreSQL metrics
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Scrape Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape process metrics
  - job_name: "process"
    static_configs:
      - targets: ["process-exporter:9256"]
  